version: '3'

services:
  container-pgdb:
    image: postgres:14.2-alpine
    container_name: container-pgdb
    environment:
      - POSTGRES_DATABASE=appDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgresql/create_db.sh:/docker-entrypoint-initdp.d/create_db.sh
      - postgres-data:/data/db

    restart: on-failure

volumes:
  postgres-data:
