version: '3'

services:
  container-pgdb:
    image: postgres:11.3-alpine
    container_name: container-pgdb
    environment:
      - POSTGRES_DATABASE=appdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres-data:/data/db

    restart: on-failure

volumes:
  postgres-data:
